name: "Terraform Apply (Main)"

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-main
  cancel-in-progress: false

jobs:

  terraform-apply:
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # ---------- Azure Login ----------
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
           with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---------- Terraform Init ----------
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: Environment/dev
      # ---------- Terraform Plan ----------
      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        working-directory: Environment/dev
      # ---------- Terraform Apply ----------
      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: Environment/dev


  terraform-destroy:
    runs-on: self-hosted
    needs: terraform-apply
    if: github.ref == 'refs/heads/main'
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: Environment/dev

      - name: Terraform Destroy
        run: terraform destroy --auto-approve
        working-directory: Environment/dev
