name: "Terraform Main (Plan + Apply with Approval)"

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-main
  cancel-in-progress: false

jobs:
  terraform-apply:
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      # ---------- Azure Login ----------
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
           with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---------- Terraform Init ----------
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: Environment/dev

       # ðŸ”¹ Generate plan file
      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan
        working-directory: Environment/dev

      # ðŸ”¹ Upload plan as artifact
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Environment/dev/tfplan

   terraform-apply:
    needs: terraform-plan
    runs-on: self-hosted
    environment: dev   # ðŸ‘ˆ MANUAL APPROVAL HAPPENS HERE

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ðŸ”¹ Download approved plan
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: Environment/dev

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: Environment/dev

      # ðŸ”¹ Apply exactly the approved plan
      - name: Terraform Apply (Approved Plan)
        run: terraform apply -auto-approve tfplan
        working-directory: Environment/dev
        
      # # ---------- Terraform Plan ----------
      # - name: Terraform Plan
      #   run: terraform plan -no-color -input=false
      #   working-directory: Environment/dev
      # # ---------- Terraform Apply ----------
      # - name: Terraform Apply
      #   run: terraform apply --auto-approve
      #   working-directory: Environment/dev


  # terraform-destroy:
  #   runs-on: self-hosted
  #   needs: terraform-apply
  #   if: github.ref == 'refs/heads/main'
  #   environment: dev

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v5.0.0

  #     - name: Azure Login
  #       uses: Azure/login@v2.3.0
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - name: Terraform Init
  #       run: terraform init -input=false
  #       working-directory: Environment/dev

  #     - name: Terraform Destroy
  #       run: terraform destroy --auto-approve
  #       working-directory: Environment/dev
